from pylab import *
import os
import sys
from radDecayParser2 import *
from radiationSolver import *
# The last two libraries define all the function and classes we need to solve for the decay chains.
# WARNING: These libraries assume that the RadioactiveDecay6.1.2 database is in the working dir.

"""
Analysis STEP 2:
determination of the decay chains for each isotope generated in the simulation
"""

input_stem = "output/scorefile"
n_prim = 100_000_000
mass_model = 'XGIS_M7'
total_n_volumes = 23
energies = [5,   6,   7,  10,  15,  20,  30,  40,  50,  60,  70, 100, 150, 200, 300, 400]
#energies = [4, 6, 8, 10, 15, 20, 30, 50, 60, 80, 100, 150, 200, 300, 400, 700]

for energy in energies:
    # Files generated by the 1_postRun_step0_reduce_scorefile.py script
    volumelistFilename = f"{input_stem}_{energy}_MeV_{n_prim:.0e}_volumelist.dat"
    reportFilename     = f"{input_stem}_{energy}_MeV_{n_prim:.0e}_report.dat"

    # Load the ASCII file with the list of the (activated) volumes in the mass model and store the names in a list.
    volumes = []
    with open(volumelistFilename, 'r') as f:
        for line in f:
            volumes.append(line.strip("\n"))
    
    print("List of all the volumes activated in this simulation:\n", volumes,"\n")
    
    # Load the simulation report.
    # This is an ASCII file with the following structure
    #    VOL volumeName0
    #    radioisotopeName0 efficiency
    #    ...
    #    VOL volumeName1
    #    radioisotopeName1 efficiency
    #    ...
    # where "efficiency" is the number of generated radioisotopes
    # in that volume for each primary event of the simulation
    # (i.e.: no. of radioisotopes in volume/no. of primaries)
    
    # Initialise a dictionary with key=volume, value=list of isotopes (empty for now) 
    sim_dict = {}
    for volume in volumes:
        sim_dict[volume] = []
    # Get the list of all isotopes generated in the simulation
    isotopeList = []
    with open(reportFilename, 'r') as f:
        for line in f:
            if line[:3] == "VOL":
                volumeName = line.split()[1]
            else:
                isotopeName = line.split()[0]
                isotopeList.append(isotopeName)
                if volumeName is not None:
                    sim_dict[volumeName].append(isotopeName)

    isotopeList = sorted(list(set(isotopeList)))
    print("List of all the generated isotopes:\n", isotopeList, "\n")

    print("Dictionary of generated isotopes in each volume:\n", sim_dict, "\n")
    

    # Calculate linearised decay chains for each isotope in the list
    # A tree structure is built for each isotope
    # and then traversed to find all decay chains,
    # which are then added to a dictionary.
    # Branching chains are treated as independent chains with a total probability.

    decay_chains = {}
    pruneThreshold = 0.01 # Threshold for branching ratios (below that value the branch is discarded)
    decay_chains_pruned = {}

    if not os.path.exists("DecayChains"):
        os.makedirs("DecayChains")

    print("\n*** Generation of decay chains ***\n")

    for rootIsotope in isotopeList:
        print("Isotope:\t\t", rootIsotope)
        
        if rootIsotope == "Eu140" or rootIsotope == "Gd140" or rootIsotope == "Y92" or rootIsotope == "Sb128" or rootIsotope == "Dy142" or rootIsotope == "Sn128" or rootIsotope == "Tc102":
            # Problematic isotopes!
            continue

        # Get isotope info
        element_name, isoZ, isoA, excitationEnergy = split_element_string(rootIsotope)
    
        print("Element:\t\t", element_name)
        print("Atomic number:\t\t", isoZ)
        print("Mass number:\t\t", isoA)
        print("Excitation energy:\t", excitationEnergy, "keV")
        print()
    
        # Check if its decay chain hasn't already calculated.
        if excitationEnergy == 0.0:
            fileout = "DecayChains/" + element_name + str(isoA) + ".dat"
        else:
            fileout = "DecayChains/" + element_name + str(isoA) + "[{:.3f}].dat".format(excitationEnergy)
        if os.path.exists(fileout):
            print("Decay chain already calculated. Skipping...\n")
        else:
            # This list will store all the decay chains for the root radioisotope
            # accounting also for the branching ratios
            chain = []

            # Initialise the root node and the stack
            # Node structure is: node = [(Z, A, excitation), halfLife, branchingRatio]
            # For the root node halfLife and branchingRatio are undefined (=None)
            rootNode = [(isoZ, isoA, excitationEnergy), None, None]
            stack = []

            # Push root node in the stack, as not visited
            # The stack contains a list with the node and a Boolean flag (visited/not visited)
            stack.append([rootNode, False])

            # Seek index (for tree traversal) initialised at root node
            seek = rootNode 

            # Loop until all nodes are visited
            allVisited = False

            while not allVisited:
                # Get daughters
                try:
                    daughters = getDecay(seek[0][0], seek[0][1], excitationEnergy=seek[0][2], verbose=False)
                except FileNotFoundError:
                    daughters = None
                # Mark last stack element as visited
                stack[-1][1] = True

                # If the node has daughters, append to the stack in reverse order
                if daughters is not None and len(daughters.daughters) > 0:
                    for d in daughters.daughters[::-1]:
                        # print(d)
                        stack.append([d, False])

                    # Mark last element as visited and put seek index there:
                    stack[-1][1] = True
                    seek = stack[-1][0]

                # If no further daughters, we have found the whole sub-chain
                else:
                    # print("Found stable")
                    # The chain is composed of all visited elements
                    subchain = [k[0] for k in stack if k[1]]
        
                    # Append the chain just found to the list for this root isotope
                    chain.append(subchain)

                    # Backtrack to last non visited node (with flag False)
                    ikill = 0
                    for i in range(len(stack)-1,-1,-1):
                        if stack[i][1] == False:
                            ikill = i
                            break

                    # Delete the subchain we have found from the stack:
                    stack = stack[:ikill+1]

                    # Put the seek index to last non visited node
                    seek = stack[ikill][0]
        
                    # Check if all nodes visited
                    allVisited = np.all([k[1] for k in stack])
            decay_chains[rootIsotope] = chain
    
            # Prune decay chains: remove all branching ratios below pruneThreshold
            # and renormalise BRs
            for key, chains in decay_chains.items():
                print(key)
                prune = []
                for i,d in enumerate(chains):
                    br = 1
                    for x in d:
                        if x[-1] is not None:
                            br *= x[-1]
                    print("\tChain no.", i, "Branching ratio:", br)
                    if br < pruneThreshold:
                        print("\t ---> WILL BE PRUNED")
                        prune.append(d)
                    if len(d) == 1:
                        print("\t ---> NO DAUGHTERS, WILL BE PRUNED")
                for p in prune:
                    chains.remove(p)
                decay_chains_pruned[key] = chains
    
            # Final formatting
            # for key, chains in decay_chains_pruned.items():
            #     print("#", key, "Decay Chain")
            #     print("# HalfLife (Z_daughter, A_daughter, E_daughter)")
            #     tot_br = 0
            #     for d in chains:
            #         tot_br += np.product([x[-1] for x in d if x[-1] is not None])
            #     for i,d in enumerate(chains):
            #         br = np.product([x[-1] for x in d if x[-1] is not None])/tot_br
            #         print("# Chain n.", i,"Branching ratio: {:.4f}".format(br))
            #         for p in d[1:]:
            #             print("{:.4e} ".format(p[1]), p[0])
                
            # Write output file 
            # The file is in DecayChains directory
            # Filename: ElementA.dat
            for key, chains in decay_chains_pruned.items():
                with open(fileout, "w") as fo:
                    fo.write("# " +  key + " Decay Chain\n")
                    fo.write("# HalfLife[s] (Z_daughter, A_daughter, E_daughter)\n")

                    tot_br = 0
                    for d in chains:
                        tot_br += np.product([x[-1] for x in d if x[-1] is not None])
                    for i,d in enumerate(chains):
                        br = np.product([x[-1] for x in d if x[-1] is not None])/tot_br
                        fo.write("# Chain n. " + str(i) + " Branching ratio: {:.4f}\n".format(br))
                        for p in d[1:]:
                            fo.write("{:.4e} ".format(p[1]))
                            fo.write(str(p[0]))
                            fo.write("\n")

            print("\nWritten output file", fileout, "\n")

