from pylab import *
import os
import sys
import glob
from myUtilities import prettifyPlot
prettifyPlot()
from radDecayParser import *
from radiationSolver import *
# The last two libraries define all the function and classes we need to solve for the decay chains.
# WARNING: These libraries assume that the RadioactiveDecay5.6 database is in the working dir.

"""
Analysis STEP 1:
Numerical solution of the radioactive decay equations.
The output is, for each volume, a list of the activities (in Bq) for the given times, 
normalised per input primary
"""

input_stem = "output/scorefile"
n_prim = 100_000_000
mass_model = 'XGIS_M7'
energies = [7,  10,  15,  20,  30,  40,  50,  60,  70, 100, 150, 200, 300, 400]
# energies = [8, 10, 15, 20, 30, 50, 60, 80, 100, 150, 200, 300, 400, 700]

fluence_normalisation = n_prim  # Fluence normalisation corresponding to n_primaries input protons, in protons/cm2
# Define the array of times in which to calculate activity
times = np.array([0.1, 1., 10., 100., 1000., 10000., 100000., 1000000., 10000000., 100000000.])
# times = np.logspace(-2,19, 256)

for energy in energies:
    # Files generated by the 1_postRun_step0_reduce_scorefile.py script
    volumelistFilename = f"{input_stem}_{energy}_MeV_{n_prim:.0e}_volumelist.dat"
    reportFilename     = f"{input_stem}_{energy}_MeV_{n_prim:.0e}_report.dat"

    # Load the ASCII file with the list of the volumes in the mass model and store the names in a list.
    volumes = []
    with open(volumelistFilename, 'r') as f:
        for line in f:
            volumes.append(line.strip("\n"))
    
    print("List of all the volumes activated in this simulation:\n", volumes,"\n")

    # Initialise an empty dictionary with key=volume, value=[isotope, [norm. activities for t in times]]
    sim_dict = {}
    for volume in volumes:
        sim_dict[volume] = []

    print("Initialised dictionary of normalised activities in each volume:\n", sim_dict, "\n")


    # Now we calculate the normalised activity for each initial isotope and each time
    # The activity is by definition A = lambda*N
    # where N is the number of generated isotopes in the simulation (efficiency*n_primaries)
    # Normalised activity is A/fluence_normalisation --> Bq/(protons/cm2)
    with open(reportFilename) as f:
        for line in f:
            if line[:3] == "VOL":
                volumeName = line.split()[1]
            else:
                isotopeName = line.split()[0]
                isotopeEff = float(line.split()[1])
                if volumeName is not None:
                    try:
                        decay_constant = get_decay_constant(isotopeName)
                        sim_dict[volumeName].append([isotopeName, int(isotopeEff*n_prim)/fluence_normalisation*decay_constant])
                    except FileNotFoundError:
                        print(f"Isotope {isotopeName} not found in RadioactiveDecay database!!!")
                    except AttributeError:
                        print(f"Isotope {isotopeName} attribute error!!!")
                        
    print("Dictionary of initial activities in each volume:\n", sim_dict, "\n")
    for key, value in sim_dict.items():
        print("Volume", key)
        for isotopeName, normAct in value:
            print("Isotope:", isotopeName, "Initial normalised activity:", normAct, "Bq/(protons/cm^2)")


    # Now we should get also the daughters for each initial isotopes, if unstable!
    # We have to loop back and parse the DecayChain/*.dat files. 
    # These are already pruned, so if decay length is >2 we add the middle unstable isotopes
    # to the dictionary of (normalised) activities.

    activities_in_volumes = {}
    for key, value in sim_dict.items():
        print("In volume", key, "we have the following isotopes:")

        # Initialise empty dictionary for activities in this volume
        activities = {}

        for isotopeName, mother_activity in value:
            print("\tIsotope", isotopeName)
            print("\t\twith an initial normalised activity of {:.4e} Bq/(protons/cm2)".format(mother_activity))
            d = get_daughters(isotopeName)
            if d is None:
                print("*** ISOTOPE", isotopeName, "NOT FOUND!")
            else:
                print("\t\tThe decay chain has", len(d), "branch(es):")
                for br, daughters in d.items():
                    print("\t\t\tBranching ratio", br)
                    chain_length = len(daughters)
                    print("\t\t\tChain length", chain_length)
                    half_lives = np.array([x[0] for x in daughters])
                    decay_constants = 0.693147/half_lives
                    print("\t\t\tHalf-lives", half_lives)
                    print("\t\t\tDecay_constants", decay_constants)
                
                    if chain_length == 0: 
                        print("This shouldn't happen. Maybe it is Tb143 or Lu162? (known bug)")
                    
                    if chain_length == 1:
                        # If only one daughter, the solution is analytical
                        # and we do not need to fully solve the Bateman equation
                        print("\t\t\tChain has only one daughter, simple solution")
                        chain_isotopes = [isotopeName]
                        Z, A, E = daughters[-1][1]
                        print("\t\t\tChain:", chain_isotopes, "( -> stable", formatElementString(Z, A, E), ")")
                        # The mother is the only unstable isotope
                        # Daughter is stable
                        concentration = np.exp(-decay_constants*times)
                        # Clip values
                        concentration[concentration < 1e-128] = 0.0
                        if isotopeName not in activities.keys():
                            activities[isotopeName] = concentration * mother_activity * br
                        else:
                            print("Isotope",  isotopeName, "has been already tracked. Summing concentrations...")
                            activities[isotopeName] += concentration * mother_activity * br
                
                    elif chain_length > 1:
                        # There is more than one daughter. We need to fully solve
                        # the Bateman equation at the times specified
                        print("\t\t\tChain has", chain_length, "daughters, full solution")
                        chain_isotopes = [isotopeName]
                        for d in daughters[:-1]:
                            Z, A, E = d[1]
                            chain_isotopes.append(formatElementString(Z, A, E))
                        Z, A, E = daughters[-1][1]
                        print("\t\t\tChain:", chain_isotopes, "( -> stable", formatElementString(Z, A, E), ")")
                    
                        if not ("B8" in chain_isotopes or "Li8" in chain_isotopes or "Tb143" in chain_isotopes):
                
                            initial_concentrations = np.zeros(chain_length)
                            initial_concentrations[0] = 1.0
                            try:
                                sol = solve_bateman_equation_Onega(decay_constants, initial_concentrations, times)
                            except TypeError:
                                continue
                            for i, conc_t in enumerate(sol):
                                # Loop on each isotope in the decay chain and clip values
                                conc_t[conc_t < 1e-128] = 0.0
                                if chain_isotopes[i] not in activities.keys():
                                    activities[chain_isotopes[i]] = (conc_t * decay_constants[i]) * mother_activity/decay_constants[0] * br
                                else:
                                    print("Isotope", chain_isotopes[i], "has been already tracked. Summing concentrations...")
                                    activities[chain_isotopes[i]] += (conc_t * decay_constants[i]) * mother_activity/decay_constants[0] * br
                        else:
                            # TODO: how to handle?
                            print("Skipping...")                
                    else:
                        pass
        activities_in_volumes[key] = activities
    
    
    print("\nSummary")
    for volume, act in activities_in_volumes.items():
        for iso, a in act.items():
            print(volume, iso, a)
            
    # Get the irradiation output filename
    irradiation = reportFilename.replace("_report.dat", "")
    outputfile = irradiation + "_activities.dat"
    print("Output will be written in ", outputfile, "\n")

    # Write output file
    activity_matrix = []
    with open(outputfile, "w") as fout:
        fout.write("# Normalised concentrations at the specified times\n")
        fout.write("# times ")
        for t in times:
            fout.write("{:.2e} ".format(t))
        fout.write("\n")
        for volume, act in activities_in_volumes.items():
            for iso, a in act.items():
                activity_matrix.append(a)
                fout.write("{} {} ".format(volume, iso))
                for at in a:
                    fout.write("{:.4e} ".format(at))
                fout.write("\n")
    activity_matrix = np.array(activity_matrix)


    # Plot total normalised activities            
    figure()
    loglog(times, activity_matrix.sum(axis=0), 'o-')
    xlabel("Time since irradiation [s]")
    ylabel("Norm. activity [Bq/protons]")
    title(f"Irradiation with {energy} MeV protons")
    grid()
    savetxt(f"plots/{energy}_MeV_total_normalised_activity.dat", list(zip(times, activity_matrix.sum(axis=0))), fmt="%.4e %.4e")
    savefig(f"plots/{energy}_MeV_total_normalised_activity.pdf", bbox_inches="tight")

    volume_isotope_to_simulate = {}
    
    for volume, act in activities_in_volumes.items():
        volume_isotope_to_simulate[volume] = []
        for iso, a in act.items():
            if np.any(a > 0.):
                volume_isotope_to_simulate[volume].append(iso)
    
    
    # Get list of isotopes to simulate in each volume
    if not os.path.exists("isotope_list_for_each_volume"):
        os.makedirs("isotope_list_for_each_volume")
    
    print(volume_isotope_to_simulate)
    for volume, isotopes in volume_isotope_to_simulate.items():
        if len(isotopes) > 0:
            print(volume)
            filename = "isotope_list_for_each_volume/{}.dat".format(volume)
            with open(filename, "a") as fout:
                for iso in isotopes:
                    print(iso)
                    alphabetic, Z, A, E = split_element_string(iso)
                    fout.write("{} {} {} {:.3f}\n".format(iso, Z, A, float(E)))
    
print("Sorting...")

for filein in sorted(glob.glob("isotope_list_for_each_volume/*.dat")):
    os.system(f"sort {filein} | uniq > {filein}_sorted")
    os.system(f"mv {filein}_sorted {filein}")
    
    print(f"sorted {filein}")
    
print("End.")

