#!/usr/bin/env python3
"""
Report C: unstable levels without decay data in RadioactiveDecay6.1.2.

Lists the ENSDFSTATE levels with 1 s <= T1/2 < 1e15 s that have no matching
level in the decay library, following the matching rules of
G4VRadioactiveDecay::LoadDecayTable.  Excited levels without a floating flag
are excluded, because Geant4 de-excites them by IT anyway.

Optionally it writes an rdecay01 macro that creates and decays every listed
level, and classifies the rdecay01 output of that macro.

Standard library only.
Usage:
    python3 check_C_no_decay_data.py [RadioactiveDecay dir] [ENSDFSTATE.dat]
                                     [--macro=FILE] [--log=FILE]
    --macro=FILE  write an rdecay01 macro (200 single decays per level)
    --log=FILE    classify the output of rdecay01 run with that macro:
                  each level is "silent" (decays without any secondary),
                  "not created" (Geant4 gives back another level, usually the
                  ground state), or "decays" (emits secondaries)
Defaults: $GEANT4_DATA_DIR/RadioactiveDecay6.1.2 and
          $GEANT4_DATA_DIR/G4ENSDFSTATE3.0/ENSDFSTATE.dat
"""
import math
import os
import re
import sys
from collections import defaultdict
from pathlib import Path

TOL = 1e-2   # keV, level-energy tolerance

data = Path(os.environ.get("GEANT4_DATA_DIR", "."))
args = [a for a in sys.argv[1:] if not a.startswith("--")]
rdm = Path(args[0]) if len(args) > 0 else data / "RadioactiveDecay6.1.2"
ensdf_file = Path(args[1]) if len(args) > 1 else data / "G4ENSDFSTATE3.0" / "ENSDFSTATE.dat"

SYM = ("n H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca Sc Ti V Cr Mn Fe Co Ni Cu Zn Ga Ge "
       "As Se Br Kr Rb Sr Y Zr Nb Mo Tc Ru Rh Pd Ag Cd In Sn Sb Te I Xe Cs Ba La Ce Pr Nd Pm Sm "
       "Eu Gd Tb Dy Ho Er Tm Yb Lu Hf Ta W Re Os Ir Pt Au Hg Tl Pb Bi Po At Rn Fr Ra Ac Th Pa U "
       "Np Pu Am Cm Bk Cf Es Fm Md No Lr Rf Db Sg Bh Hs Mt Ds Rg Cn Nh Fl Mc Lv Ts Og").split()


def name(Z, A, E=0.0, flb=""):
    s = f"{SYM[Z]}{A}"
    return s + (f"[{E:g}{flb}]" if E > 0 or flb else "")


def fmt_t(t):
    for unit, sec in (("y", 3.15576e7), ("d", 86400), ("h", 3600), ("min", 60)):
        if t >= sec:
            return f"{t / sec:.4g} {unit}"
    return f"{t:.4g} s"


# ---- ENSDFSTATE: (Z, A) -> [(E keV, flb, T1/2 s or -1)] ----------------------
ensdf = defaultdict(list)
for line in open(ensdf_file):
    t = line.split()
    if len(t) >= 5:
        tau_ns = float(t[4])
        ensdf[(int(t[0]), int(t[1]))].append(
            (float(t[2]), t[3].lstrip("+-").upper(), tau_ns * 1e-9 * math.log(2) if tau_ns > 0 else -1))

# ---- RadioactiveDecay: (Z, A) -> [level dict] in file order --------------------
# summary lines: mode, 0, fraction (3 columns)
# detail lines:  mode, daughter E (keV), flag, intensity (%), Q (keV) [, beta type]
lib = {}
for f in rdm.glob("z*.a*"):
    m = re.fullmatch(r"z(\d+)\.a(\d+)", f.name)
    if not m:
        continue
    levels = []
    for line in f.read_text().splitlines():
        t = line.split()
        if not t or t[0].startswith("#"):
            continue
        if t[0] == "P":
            levels.append({"E": float(t[1]), "flb": t[2].lstrip("+-").upper(), "T": float(t[3]),
                           "summary": {}, "detail": []})
        elif levels and len(t) == 3:
            levels[-1]["summary"][t[0]] = float(t[2])
        elif levels and len(t) >= 5:
            levels[-1]["detail"].append((t[0], float(t[1]), float(t[3]), float(t[4])))
    lib[(int(m.group(1)), int(m.group(2)))] = levels


def g4_match(Z, A, E, flb):
    """Level chosen by G4VRadioactiveDecay::LoadDecayTable, or None."""
    for lv in lib.get((Z, A), []):
        if abs(lv["E"] - E) < TOL and (not flb or lv["flb"] == flb):
            return lv
    return None


print(f"RadioactiveDecay: {rdm}\nENSDFSTATE:       {ensdf_file}\n")
opts = dict(a[2:].split("=", 1) for a in sys.argv[1:] if a.startswith("--") and "=" in a)

print("ENSDFSTATE levels with 1 s <= T1/2 < 1e15 s and no decay data in the library")
missing = []
for (Z, A), levels in sorted(ensdf.items()):
    for E, flb, hl in levels:
        if 1.0 <= hl < 1e15 and g4_match(Z, A, E, flb) is None and not (E > 0 and not flb):
            missing.append((Z, A, E, flb, hl))
            where = "no file" if (Z, A) not in lib else "no level"
            print(f"   {name(Z, A, E, flb):16s} T1/2 = {fmt_t(hl):10s} ({where})")
print(f"   total: {len(missing)} (excited levels without flag are excluded: Geant4 applies IT to them)")

if "macro" in opts:
    with open(opts["macro"], "w") as f:
        f.write("# Generated by check_C_no_decay_data.py: one run of 200 single decays per level.\n"
                "# Run with the unmodified example examples/extended/radioactivedecay/rdecay01\n"
                "# and classify the output with check_C_no_decay_data.py --log=<output>.\n"
                "/control/verbose 0\n/run/verbose 0\n"
                "/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+60 year\n"
                "/run/initialize\n/gun/particle ion\n/rdecay01/fullChain false\n/run/printProgress 0\n")
        for Z, A, E, flb, hl in missing:
            f.write(f"/control/echo CASE {Z} {A} {E:g} {flb or '-'}\n"
                    f"/gun/ion {Z} {A} 0 {E:g} {flb}\n/run/beamOn 200\n")
    print(f"\nrdecay01 macro written to {opts['macro']}")

if "log" in opts:
    # Split the master output at the "CASE" echo lines; in each block read the
    # primary name ("The run was N <name> of") and the "Nb of generated particles" table.
    cases, cur = [], None
    for line in open(opts["log"], errors="replace"):
        if line.startswith("CASE "):
            cur = {"req": line.split()[1:], "primary": None, "rows": [], "table": False}
            cases.append(cur)
        elif cur is not None:
            m = re.match(r"\s*The run was \d+ (\S+) of", line)
            if m:
                cur["primary"] = m.group(1)
            elif "Nb of generated particles" in line:
                cur["table"] = True
            elif cur["table"]:
                m = re.match(r"\s*(\S+):\s+\d+\s+Emean", line)
                if m:
                    cur["rows"].append(m.group(1))
                elif cur["rows"] and not line.strip():
                    cur["table"] = False
    out = {"silent": [], "not created": [], "decays": []}
    for c in cases:
        Z, A, E, flb = int(c["req"][0]), int(c["req"][1]), float(c["req"][2]), c["req"][3].strip("-")
        m = re.fullmatch(r"([A-Za-z]+\d+)(?:\[([\d.]+)([A-Z]?)\])?", c["primary"] or "")
        got_flb = (m.group(3) or "") if m else None
        got_E = float(m.group(2)) if m and m.group(2) else 0.0
        hl = next((h for z, a, e, f, h in missing if (z, a, e, f) == (Z, A, E, flb)), -1)
        label = f"{name(Z, A, E, flb):16s} T1/2 = {fmt_t(hl):10s} Geant4 primary: {c['primary']}"
        if m is None or got_flb != flb or abs(got_E - E) > TOL:
            out["not created"].append(label)
        elif len(c["rows"]) <= 1:
            out["silent"].append(label)
        else:
            out["decays"].append(label + "  secondaries: "
                                  + ", ".join([r for r in c["rows"] if r != c["primary"]][:6]))
    print(f"\nrdecay01 results from {opts['log']} ({len(cases)} levels)")
    for k in ("silent", "not created", "decays"):
        print(f"\n  {k}: {len(out[k])}")
        for s in out[k]:
            print("   ", s)
